### PR TITLE
Feature/eui keys config

### PR DESCRIPTION
**Pull request by elsalahy**
**Summary:**

An effort to reduce the complexity of configuring the keys and EUIs for applications with SW based LoRaWAN credentials.

Relates to #133 and #56 but doesn't close them as it's a stopgap solution. 

**Changes:**

- Defaults the LoRaWAN OTAA activation information to v1.0.2  
- Adds some documentation to help users navigate to the configuration and setup the apps

**Notes for Reviewers:**

A stopgap until we make it extremely simple.
The keys order/format is exactly the same as V3 😄  to make it super simple.

**Release Notes: _(optional)_**

...

### CODE REVIEW

**Comment by elsalahy** [comment]
@azerimaker please keep the update in mind, but no need to review.

**Review by marnixcro — APPROVED** [review]
This is a really good improvement, it really solves the disconnect there is between naming conventions of the site and the GN. I tested both freefall_lorawan and basic_lorawan, both worked. Future improvement could be adding ABP keys to basic_lorawan, as it is probably the one app people are going to test ABP with.

**Comment by elsalahy** [comment]
Thanks @marnixcro for the review and feedback, it's helpful

**Comment by elsalahy** [comment]
@johanstokking would love your quick feedback on this before merging

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
