### PR TITLE
Feature/stm32 wl 1.0

### PR DESCRIPTION
**Pull request by elsalahy**
**Summary:**

Adds the[ official ST STM32WL remote HAL subtree](https://github.com/STMicroelectronics/stm32wlxx_hal_driver) V1.0.0 instead of the [personal 0.7 beta version](https://github.com/elsalahy/STM32WLxx_HAL_Driver).

This is part of #88 

**Changes:**

- Utilize STM32WL V1.0
- Update structure and remote to accommodate the change
- Update description and docs to reflect the change

**Notes for Reviewers:**

Tested all apps and they seem functional with no issues.
This is only half of V1.0 integration.

**Release Notes: _(optional)_**

Will take a beta release before merging this PR.

### CODE REVIEW

**Comment by elsalahy** [comment]
@johanstokking this looks like a major change because I had to change the subtree remote to the the new ST official remote, and effectively had to remove the older remote and rename it.

I considered a submodule approach, but we agreed #24 that this is the better approach, but please let me know if you have a different approach in mind?

P.S. Future changes will be more manageable, so I prefer the subtree approach as well

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
OK I see, indeed in some cases this is inevitable.

**Comment by elsalahy** [comment]
@azerimaker and @marnixcrouzen did you test the changes, any comments?

**Review by marnixcrouzen — APPROVED** [review]
All apps still build in Linux, all still functioning the same as develop branch.

**Pull request merged**
